#### **归一化：把不同量纲、不同取值范围的数据“拉齐”到同一尺度，避免模型“偏心”某些特征。**

| 方法名称           | 公式                                              | 特点                  |
| -------------- | ----------------------------------------------- | ------------------- |
| **Min-Max归一化** | $x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}$ | 缩放到 \[0, 1]，受异常值影响大 |
| **Z-score标准化** | $x' = \frac{x - \mu}{\sigma}$                   | 均值为0，方差为1，适用于正态分布   |
| **Robust标准化**  | $x' = \frac{x - \text{median}}{\text{IQR}}$     | 抗异常值能力强             |


In [1]:
import numpy as np
from sklearn import datasets

In [2]:
# 加载鸢尾花数据集
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

### **最大最小值归一化**

In [4]:
# 先打印出前五行 看看数据
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
# 找出第一列最大值和最小值
np.max(X[:,0]),np.min(X[:,0])

(np.float64(7.9), np.float64(4.3))

In [7]:
# 使用公式，计算出每个缩放后的值
X[:,0] = (X[:,0] - np.min(X[:,0])) / (np.max(X[:,0]) - np.min(X[:,0]))

In [9]:
# 同理，处理后面几列数据
X[:,1] = (X[:,1] - np.min(X[:,1])) / (np.max(X[:,1]) - np.min(X[:,1]))
X[:,2] = (X[:,2] - np.min(X[:,2])) / (np.max(X[:,2]) - np.min(X[:,2]))
X[:,3] = (X[:,3] - np.min(X[:,3])) / (np.max(X[:,3]) - np.min(X[:,3]))

In [10]:
X[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

### **零均值归一化**

In [11]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [12]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [13]:
# 求第一列的均值、标准差
np.mean(X[:,0]),np.std(X[:,0])

(np.float64(5.843333333333334), np.float64(0.8253012917851409))

In [14]:
X[:,0] = (X[:,0] - np.mean(X[:,0])) / np.std(X[:,0])

In [16]:
X[:,1] = (X[:,1] - np.mean(X[:,1])) / np.std(X[:,1])
X[:,2] = (X[:,2] - np.mean(X[:,2])) / np.std(X[:,2])
X[:,3] = (X[:,3] - np.mean(X[:,3])) / np.std(X[:,3])

In [17]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

### **scikit-learn中的StandardScaler**

In [18]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
standard_scaler = StandardScaler()

In [21]:
standard_scaler.fit(X)

,copy,True
,with_mean,True
,with_std,True


In [22]:
standard_scaler.mean_

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [23]:
standard_scaler.scale_

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [26]:
X = standard_scaler.transform(X)

In [27]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])