In [1]:
import numpy as np

In [2]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
a = np.array([6,6,6,6])
a

array([6, 6, 6, 6])

#### np.concatenate((array1,array2),axis) 拼接两个数组，需要相同维度

In [4]:
X = np.concatenate((A,a.reshape(1,4)))
print(X,"\n")
X_1 = np.concatenate((A,a.reshape(4,1)),axis=1)
print(X_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 6  6  6  6]] 

[[ 0  1  2  3  6]
 [ 4  5  6  7  6]
 [ 8  9 10 11  6]
 [12 13 14 15  6]]


#### 另外一种拼接方式 (不用统一数组的维度,但是还是要确保拼接方向的元素一致)：
#### 1、竖直方向的合并：np.vstack((array1,array2)) 
#### 2、水平方向的合并: np.hstack((array1,array2)) 

In [5]:
X1 = np.vstack((A,a))
X1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 6,  6,  6,  6]])

In [6]:
X2 = np.hstack((A,a.reshape(4,1)))
X2
# a.reshape(4,1)

array([[ 0,  1,  2,  3,  6],
       [ 4,  5,  6,  7,  6],
       [ 8,  9, 10, 11,  6],
       [12, 13, 14, 15,  6]])

In [7]:
b = np.arange(6).reshape(2,3)
b.T

array([[0, 3],
       [1, 4],
       [2, 5]])

#### 数组拆分

#### np.split(array,[],axis) axis默认为0，按行拆分

In [8]:
np.split(X1,[-1])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[6, 6, 6, 6]])]

In [9]:
R1,R2 = np.split(X2,[-1],axis=1)
print(R1)
print(R2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[6]
 [6]
 [6]
 [6]]


#### vsplit、hsplit

In [11]:
np.vsplit(X1,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [ 6,  6,  6,  6]])]

In [14]:
np.hsplit(X1,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [ 6]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [ 6,  6]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [ 6]])]