In [1]:
import numpy as np

In [2]:
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### python中，需要遍历列表中的每个元素才可以进行运算，numpy可以直接array*n的方式运算

In [3]:
temp = [1,2,3]
print(f'列表直接乘以2：{temp * 2}') 

# 使用numpy 可以直接对每个元素进行运算
print(f'使用np进行运算：\n{X * 2}')

列表直接乘以2：[1, 2, 3, 1, 2, 3]
使用np进行运算：
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


### 一元运算（有一个操作数）

In [4]:
X1 = np.arange(1,7,0.5).reshape(3,4)
X1

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5]])

In [5]:
# 绝对值 abs
np.abs(X1)

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5]])

In [6]:
# 开方 sqrt
np.sqrt(X1)

array([[1.        , 1.22474487, 1.41421356, 1.58113883],
       [1.73205081, 1.87082869, 2.        , 2.12132034],
       [2.23606798, 2.34520788, 2.44948974, 2.54950976]])

In [7]:
# 平方 square
np.square(X1)

array([[ 1.  ,  2.25,  4.  ,  6.25],
       [ 9.  , 12.25, 16.  , 20.25],
       [25.  , 30.25, 36.  , 42.25]])

In [8]:
# 自然常数e的指数运算 exp
np.exp(X1)

array([[  2.71828183,   4.48168907,   7.3890561 ,  12.18249396],
       [ 20.08553692,  33.11545196,  54.59815003,  90.0171313 ],
       [148.4131591 , 244.69193226, 403.42879349, 665.14163304]])

In [9]:
# 对数运算 log() - 以e为底。 logn() - 以n为底
print(np.log(X1))
print(np.log2(X1))

[[0.         0.40546511 0.69314718 0.91629073]
 [1.09861229 1.25276297 1.38629436 1.5040774 ]
 [1.60943791 1.70474809 1.79175947 1.87180218]]
[[0.         0.5849625  1.         1.32192809]
 [1.5849625  1.80735492 2.         2.169925  ]
 [2.32192809 2.45943162 2.5849625  2.70043972]]


In [10]:
# 向上取整 cell    向下取整 floor
print(np.ceil(X1))
print(np.floor(X1))

[[1. 2. 2. 3.]
 [3. 4. 4. 5.]
 [5. 6. 6. 7.]]
[[1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [5. 5. 6. 6.]]


In [11]:
# 四舍五入函数 round
np.round(X1)

array([[1., 2., 2., 2.],
       [3., 4., 4., 4.],
       [5., 6., 6., 6.]])

In [12]:
# 三角函数 sin、cos、tan
print(np.sin(X1))
print(np.cos(X1))
print(np.tan(X1))

[[ 0.84147098  0.99749499  0.90929743  0.59847214]
 [ 0.14112001 -0.35078323 -0.7568025  -0.97753012]
 [-0.95892427 -0.70554033 -0.2794155   0.21511999]]
[[ 0.54030231  0.0707372  -0.41614684 -0.80114362]
 [-0.9899925  -0.93645669 -0.65364362 -0.2107958 ]
 [ 0.28366219  0.70866977  0.96017029  0.97658763]]
[[ 1.55740772 14.10141995 -2.18503986 -0.7470223 ]
 [-0.14254654  0.37458564  1.15782128  4.63733205]
 [-3.38051501 -0.99558405 -0.29100619  0.2202772 ]]


### 二元运算（有两个操作数）

#### 最简单的二元运算 就是 加减乘除

In [14]:
# 加法
X1 + 1
# 相当于使用 np.add(X1,1)

array([[2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

In [30]:
# 乘、除
print(X1*2)
print(2*X1)
print(X1/2)

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
[[0.5  0.75 1.   1.25]
 [1.5  1.75 2.   2.25]
 [2.5  2.75 3.   3.25]]


In [17]:
# 整除、取余、幂运算
print(X1//2)
print(X1%2)
print(X1**2)

[[0. 0. 1. 1.]
 [1. 1. 2. 2.]
 [2. 2. 3. 3.]]
[[1.  1.5 0.  0.5]
 [1.  1.5 0.  0.5]
 [1.  1.5 0.  0.5]]
[[ 1.    2.25  4.    6.25]
 [ 9.   12.25 16.   20.25]
 [25.   30.25 36.   42.25]]


#### 矩阵运算

In [24]:
# 创建两个矩阵
Y = np.linspace(10,40,4).reshape(2,2)
Y1 = np.linspace(1,4,4).reshape(2,2)
Y,Y1

(array([[10., 20.],
        [30., 40.]]),
 array([[1., 2.],
        [3., 4.]]))

#### 哈达玛积（对应位置的元素相乘，不是矩阵的相乘）
#### 哈达玛积的规则：两个数组必须具有相同的形状，或者满足广播机制的兼容形状。
#### 广播机制：从最右边的维度开始向左对齐。在大小为1或缺失的维度上，通过复制数据来扩展数组，以匹配另一个数组的维度大小。

In [29]:
# 最简单的哈达玛积：标量与数组（array * n）
Y * Y1

array([[ 10.,  40.],
       [ 90., 160.]])

#### 矩阵相乘（点积） np.dot(array1,arry2) 

In [34]:
# Y.dot(Y1)
np.dot(Y,Y1)

array([[ 70., 100.],
       [150., 220.]])

In [36]:
# 对应位置相除，同样有广播机制
Y/Y1

array([[10., 10.],
       [10., 10.]])

In [42]:
# 广播机制，Y的每一行都和A点积，并将结果简化为一维输出
A = np.array([1,4])
B = np.dot(Y,A)
A,B

(array([1, 4]), array([ 90., 190.]))

In [43]:
# 广播机制，并不是把[1,4]转换成[[1,4],[1,4]]后再点积
A = np.array([[1,4],[1,4]])
np.dot(Y,A)

array([[ 30., 120.],
       [ 70., 280.]])

#### 逆矩阵 np.linalg.inv(A)

In [46]:
C = np.linalg.inv(Y)
C

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [47]:
np.dot(C,Y)

array([[1.0000000e+00, 8.8817842e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [48]:
np.dot(Y,C)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])