In [1]:
import numpy as np

In [2]:
a = np.random.normal(0,1,size=1000000)
a

array([-1.13648189,  0.15738333,  1.65146895, ..., -0.08389691,
        0.44477128,  1.03617623], shape=(1000000,))

In [11]:
# 均值、方差
np.mean(a),np.std(a)

(np.float64(-2.290579790017591e-05), np.float64(1.0005932048867237))

In [3]:
np.min(a)

np.float64(-4.851825296040713)

In [7]:
# argmin()可以找出最小元素的索引，根据索引找到的最小值与min()结果一样
print(np.argmin(a))
print(a[np.argmin(a)])

996537
-4.851825296040713


In [8]:
# argmax()同理
print(np.argmax(a))
print(a[np.argmax(a)])

596453
4.705035694101655


### 排序

In [15]:
c = np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# 使用random.shuffle,会打乱原数组的顺序，并保存在原变量中
np.random.shuffle(c)
c

array([11, 18, 17, 16,  1,  8, 13,  3, 12,  0,  2, 15,  4,  9,  6,  7, 10,
       19, 14,  5])

In [18]:
# 使用np.sort(),重新排序，顺序，不会改变原变量中的顺序
np.sort(c), c

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([11, 18, 17, 16,  1,  8, 13,  3, 12,  0,  2, 15,  4,  9,  6,  7, 10,
        19, 14,  5]))

In [29]:
# 使用python原生sort() 可以修改原变量
d = c
d.sort()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
# 使用切片来实现倒序 d[::-1]
d[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### 使用索引

In [47]:
np.random.shuffle(c)
c

array([14, 16,  9,  5,  6,  7,  4,  0, 17, 18, 10,  3, 11, 12, 15, 13, 19,
        8,  2,  1])

In [49]:
# 返回正序元素的索引
np.argsort(c)

array([ 7, 19, 18, 11,  6,  3,  4,  5, 17,  2, 10, 12, 13, 15,  0, 14,  1,
        8,  9, 16])

### partition分区 将数组部分排序，使得第k小的元素在正确的位置上
### np.partition(a, kth, axis=-1, kind='introselect', order=None)

In [50]:
np.partition(c,5)

array([ 0,  1,  4,  2,  3,  5,  6,  7,  9,  8, 10, 11, 12, 13, 14, 15, 19,
       16, 17, 18])

In [51]:
np.partition(c,[5,10])

array([ 0,  1,  4,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 19,
       16, 17, 18])

In [53]:
# np.argpartition(),返回索引
np.argpartition(c,5)

array([ 7, 19,  6, 18, 11,  3,  4,  5,  2, 17, 10, 12, 13, 15,  0, 14, 16,
        1,  8,  9])

### 高维的情况

In [54]:
X = np.random.randint(10,size=(5,5))
X

array([[1, 6, 1, 6, 5],
       [8, 3, 0, 5, 2],
       [5, 8, 5, 6, 9],
       [5, 6, 2, 7, 8],
       [0, 0, 6, 9, 9]], dtype=int32)

In [55]:
# np.sort() 默认以最高维度排序。二维axis=1,按列；三维axis=2
np.sort(X)

array([[1, 1, 5, 6, 6],
       [0, 2, 3, 5, 8],
       [5, 5, 6, 8, 9],
       [2, 5, 6, 7, 8],
       [0, 0, 6, 9, 9]], dtype=int32)

In [57]:
np.sort(X,axis=0)

array([[0, 0, 0, 5, 2],
       [1, 3, 1, 6, 5],
       [5, 6, 2, 6, 8],
       [5, 6, 5, 7, 9],
       [8, 8, 6, 9, 9]], dtype=int32)