In [1]:
import numpy as np

In [3]:
# x = np.random.randint(1,10,10)
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 从索引为2一直取到6(不包括6)，步长为1
x[2:6:1]

array([2, 3, 4, 5])

In [7]:
# 使用神奇索引
index = [2,4,6,8]
x[index]

array([2, 4, 6, 8])

In [4]:
# 索引是二维的，结果也会是二维的
# 传入的值可以是数组，也可以不是
index = [[1,3,5],[2,4,6]]
index_r = np.array([[1,3,5],[2,4,6]])
x[index],x[index_r]

(array([[1, 3, 5],
        [2, 4, 6]]),
 array([[1, 3, 5],
        [2, 4, 6]]))

### 神奇索引用于二维数组

In [14]:
X = x.reshape(2,-1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
# 取出 (0,0)、(1,2)、(0,4)
row = np.array([0,1,0])
col = np.array([0,2,4])
X[row,col]

array([0, 7, 4])

In [40]:
# 取出 (0,2)、(0,4)、(0,1)
X[0,[2,4,1]]

array([2, 4, 1])

### 比较
### 比较结果和神奇索引的使用

In [41]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# x>5 返回出True或False
x>5,x[x>5]

(array([False, False, False, False, False, False,  True,  True,  True,
         True]),
 array([6, 7, 8, 9]))

In [44]:
x[x%2==0]

array([0, 2, 4, 6, 8])

### 比较的更多应用

In [49]:
# count_nonzero()返回数组中不是0的元素个数，但是，x<5返回的是bool类型，所以包括0
np.count_nonzero(x),np.count_nonzero(x<5)

(np.int64(9), np.int64(5))

In [51]:
# any()函数
np.any(x>5)

np.True_

In [52]:
# all()
np.all(x>0)

np.False_

In [55]:
# sum()
np.sum(x%2==0)

np.int64(5)

In [61]:
X = x.reshape(2,-1)
# axis=几，就把第几维“压扁”，结果就是剩余的维数
np.sum(X%2==0,axis=1),np.sum(X%2==0,axis=0)
# 例：原维度是(2,5)，axis=1时，1维被压缩去掉，剩余0维(2,)

(array([3, 2]), array([1, 1, 1, 1, 1]))

### 与& 或| 非~

In [63]:
x[(x>3)&(x<8)]

array([4, 5, 6, 7])

In [68]:
np.all((x<2)|(x>8)),np.any((x<2)|(x>8))

(np.False_, np.True_)