In [1]:
import numpy as np

In [2]:
# x = np.random.randint(1,10,10)
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 从索引为2一直取到6(不包括6)，步长为1
x[2:6:1]

array([2, 3, 4, 5])

In [7]:
# 使用神奇索引
index = [2,4,6,8]
x[index]

array([2, 4, 6, 8])

In [12]:
# 索引是二维的，结果也会是二维的
# 传入的值可以是数组，也可以不是
index = [[1,3,5],[2,4,6]]
index_r = np.array([[1,3,5],[2,4,6]])
x[index],x[index_r]

(array([[1, 3, 5],
        [2, 4, 6]]),
 array([[1, 3, 5],
        [2, 4, 6]]))